### PR TITLE
added missing image for jQuery UI autocomplete

### PR DESCRIPTION
**Pull request by calvinhp**

### CODE REVIEW

**Comment by keul** [comment]
Hi @calvinhp, I think you can automatically merge this. I fear we have no maintainer for this add-on to evaluate a PR.

**Comment by sithmel** [comment]
Hi, 
I don't have time to maintain this product anymore.
@calvinhp you can go on and merge if you wish.
@keul Are you willing to "adopt" this product ? :-) if you need the pypi permissions just let me know.

**Comment by keul** [comment]
@sithmel yes I can, I still use it in a bunch on projects!
I'm `keul` on both pypi and plone.org

Thanks!

**Comment by sithmel** [comment]
done. All yours :-)

On 3 February 2015 at 10:23, Luca Fabbri <notifications@github.com> wrote:

> @sithmel <https://github.com/sithmel> yes I can, I still use it in a
> bunch on projects!
> I'm keul on both pypi and plone.org
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/collective/Products.Maps/pull/3#issuecomment-72626884>
> .
>



-- 
Maurizio Lupo
http://twitter.com/sithmel <http://twitter.com/#!/sithmel>

**Pull request merged**
